// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MichaelsPathFinderRazorPages.Migrations
{
    [DbContext(typeof(MichaelsPathfinderRazorPagesContext))]
    [Migration("20220219040611_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("MichaelsPathFinderRazorPages.Models.Feats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FeatLearnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("featName")
                        .HasColumnType("TEXT");

                    b.Property<string>("shortDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Feats");
                });
#pragma warning restore 612, 618
        }
    }
}
